#!/bin/bash
if [[ "$1" = "" ]]; then
    echo 'Usage: random_comp path/to/output/dir num_of_trials [ options to gen-inpu.py ]'
    exit 1
fi

DIR=$1
shift

N=$1
shift 

for i in $(seq 1 $N); do 
    GEN=$(./gen-input.py $@)
    echo gen done 

    for PY in ./mikami_tabuchi.py ./steiner_tree.py ./maze_lee.py ./mod_a_star.py; do
        mkdir -p ./$DIR/"$PY"/{in,out,err}

        F="$(mktemp XXXXX -u)"
        IN="./$DIR/$PY/in/$F.json"
        OUT="./$DIR/$PY/out/$F.json"
        ERR="./$DIR/$PY/err/$F.txt"

        echo "$IN" '->' "$OUT" , "$ERR"
        echo $GEN >"$IN"

        /usr/bin/time -f%e timeout 5m python3 $PY <"$IN" 2>"$ERR" | python3 ./calc_total.py >"$OUT"

        echo $PY done
        ./verify.py "$IN" "$OUT" 
    done
done
